name: J T G
favicon: null
layout_spectrum: 0.6876
typography_spectrum: 0.83839
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8e2e1'
    - '#090a0e'
    - '#595a5e'
    - '#839997'
    - '#b6c0c0'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
